# Generated by Django 5.0.6 on 2024-05-28 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='products',
            field=models.ManyToManyField(blank=True, to='marketplace.product'),
        ),
        migrations.AddField(
            model_name='userlibrary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to=settings.AUTH_USER_MODEL),
        ),
    ]
